# Site settings
title: WPHercules Terms and Conditions
description: >- # this means to ignore newlines until "baseurl:"
  WPHercules Terms and Conditions
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://terms.wphercules.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
theme: cayman
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
