# Site settings
title: WPHercules Terms and Conditions
description: WPHercules Terms and Conditions and Privacy Policy

# Build settings
markdown: kramdown
theme: minima

plugins:
  - jekyll-titles-from-headings
  
titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true รง

header_pages:
  - Terms_of_Service.md
  - privacy.md